<?php

namespace App\Database\Seeds;
use CodeIgniter\I18n\Time;

use CodeIgniter\Database\Seeder;

class u11_ChannelPembayaranSeederSeeder extends Seeder
{
    public function run()
    {
        $data = [
            // FIXED VIRTUAL ACCOUNT
            [
                'channel_pembayaran_id' => 1,
                'type'                  => 'VIRTUAL ACCOUNT',
                'type_transaksi'        => 'Terima',
                'nama_channel'          => 'Mandiri VA',
                'kode_xendit'           => 'MANDIRI',
                'xendit_fee'            => 4500,
                'xendit_fee_percent'    => '',
                'kode_midtrans'         => '',
                'midtrans_fee'          => '',
                'midtrans_fee_percent'  => '',
                'kode_ipaymu'           => '',
                'ipaymu_fee'            => '',
                'ipaymu_fee_percent'    => '',
                'use_payment_gateway'   => 'xendit',
                'get_profit_fee'        => '',
                'get_profit_percent'    => 1500,
                'status_channel'        => 'NonAktif',
                'created_at'            => Time::now(),
                'update_at'             => Time::now()
            ],
            [
                'channel_pembayaran_id' => 2,
                'type'                  => 'VIRTUAL ACCOUNT',
                'type_transaksi'        => 'Terima',
                'nama_channel'          => 'BRI VA',
                'kode_xendit'           => 'BRI',
                'xendit_fee'            => 4500,
                'xendit_fee_percent'    => '',
                'kode_midtrans'         => '',
                'midtrans_fee'          => '',
                'midtrans_fee_percent'  => '',
                'kode_ipaymu'           => '',
                'ipaymu_fee'            => '',
                'ipaymu_fee_percent'    => '',
                'use_payment_gateway'   => 'xendit',
                'get_profit_fee'        => '',
                'get_profit_percent'    => 1500,
                'status_channel'        => 'NonAktif',
                'created_at'            => Time::now(),
                'update_at'             => Time::now()
            ],
            [
                'channel_pembayaran_id' => 3,
                'type'                  => 'VIRTUAL ACCOUNT',
                'type_transaksi'        => 'Terima',
                'nama_channel'          => 'BNI VA',
                'kode_xendit'           => 'BNI',
                'xendit_fee'            => 4500,
                'xendit_fee_percent'    => '',
                'kode_midtrans'         => '',
                'midtrans_fee'          => '',
                'midtrans_fee_percent'  => '',
                'kode_ipaymu'           => '',
                'ipaymu_fee'            => '',
                'ipaymu_fee_percent'    => '',
                'use_payment_gateway'   => 'xendit',
                'get_profit_fee'        => '',
                'get_profit_percent'    => 1500,
                'status_channel'        => 'NonAktif',
                'created_at'            => Time::now(),
                'update_at'             => Time::now()
            ],
            [
                'channel_pembayaran_id' => 4,
                'type'                  => 'VIRTUAL ACCOUNT',
                'type_transaksi'        => 'Terima',
                'nama_channel'          => 'BCA VA',
                'kode_xendit'           => 'BCA',
                'xendit_fee'            => 4500,
                'xendit_fee_percent'    => '',
                'kode_midtrans'         => '',
                'midtrans_fee'          => '',
                'midtrans_fee_percent'  => '',
                'kode_ipaymu'           => '',
                'ipaymu_fee'            => '',
                'ipaymu_fee_percent'    => '',
                'use_payment_gateway'   => 'xendit',
                'get_profit_fee'        => '',
                'get_profit_percent'    => 1500,
                'status_channel'        => 'NonAktif',
                'created_at'            => Time::now(),
                'update_at'             => Time::now()
            ],
            [
                'channel_pembayaran_id' => 5,
                'type'                  => 'VIRTUAL ACCOUNT',
                'type_transaksi'        => 'Terima',
                'nama_channel'          => 'BJB VA',
                'kode_xendit'           => 'BJB',
                'xendit_fee'            => 4500,
                'xendit_fee_percent'    => '',
                'kode_midtrans'         => '',
                'midtrans_fee'          => '',
                'midtrans_fee_percent'  => '',
                'kode_ipaymu'           => '',
                'ipaymu_fee'            => '',
                'ipaymu_fee_percent'    => '',
                'use_payment_gateway'   => 'xendit',
                'get_profit_fee'        => '',
                'get_profit_percent'    => 1500,
                'status_channel'        => 'NonAktif',
                'created_at'            => Time::now(),
                'update_at'             => Time::now()
            ],
            [
                'channel_pembayaran_id' => 6,
                'type'                  => 'VIRTUAL ACCOUNT',
                'type_transaksi'        => 'Terima',
                'nama_channel'          => 'PERMATA VA',
                'kode_xendit'           => 'PERMATA',
                'xendit_fee'            => 4500,
                'xendit_fee_percent'    => '',
                'kode_midtrans'         => '',
                'midtrans_fee'          => '',
                'midtrans_fee_percent'  => '',
                'kode_ipaymu'           => '',
                'ipaymu_fee'            => '',
                'ipaymu_fee_percent'    => '',
                'use_payment_gateway'   => 'xendit',
                'get_profit_fee'        => '',
                'get_profit_percent'    => 1500,
                'status_channel'        => 'NonAktif',
                'created_at'            => Time::now(),
                'update_at'             => Time::now()
            ],
            [
                'channel_pembayaran_id' => 7,
                'type'                  => 'VIRTUAL ACCOUNT',
                'type_transaksi'        => 'Terima',
                'nama_channel'          => 'SAMPOERNA VA',
                'kode_xendit'           => 'SAHABAT_SAMPOERNA',
                'xendit_fee'            => 4500,
                'xendit_fee_percent'    => '',
                'kode_midtrans'         => '',
                'midtrans_fee'          => '',
                'midtrans_fee_percent'  => '',
                'kode_ipaymu'           => '',
                'ipaymu_fee'            => '',
                'ipaymu_fee_percent'    => '',
                'use_payment_gateway'   => 'xendit',
                'get_profit_fee'        => '',
                'get_profit_percent'    => 1500,
                'status_channel'        => 'NonAktif',
                'created_at'            => Time::now(),
                'update_at'             => Time::now()
            ],
            [
                'channel_pembayaran_id' => 8,
                'type'                  => 'VIRTUAL ACCOUNT',
                'type_transaksi'        => 'Terima',
                'nama_channel'          => 'BSI VA',
                'kode_xendit'           => 'BSI',
                'xendit_fee'            => 4500,
                'xendit_fee_percent'    => '',
                'kode_midtrans'         => '',
                'midtrans_fee'          => '',
                'midtrans_fee_percent'  => '',
                'kode_ipaymu'           => '',
                'ipaymu_fee'            => '',
                'ipaymu_fee_percent'    => '',
                'use_payment_gateway'   => 'xendit',
                'get_profit_fee'        => '',
                'get_profit_percent'    => 1500,
                'status_channel'        => 'NonAktif',
                'created_at'            => Time::now(),
                'update_at'             => Time::now()
            ],
            // Ewalet
            [
                'channel_pembayaran_id' => 9,
                'type'                  => 'E-WALLET',
                'type_transaksi'        => 'Terima',
                'nama_channel'          => 'OVO',
                'kode_xendit'           => 'OVO',
                'xendit_fee'            => '',
                'xendit_fee_percent'    => 1.5,
                'kode_midtrans'         => '',
                'midtrans_fee'          => '',
                'midtrans_fee_percent'  => '',
                'kode_ipaymu'           => '',
                'ipaymu_fee'            => '',
                'ipaymu_fee_percent'    => '',
                'use_payment_gateway'   => 'xendit',
                'get_profit_fee'        => 0.5,
                'get_profit_percent'    => '',
                'status_channel'        => 'NonAktif'                'created_at'            => Time::now(),
                'update_at'             => Time::now()
            ],
            [
                'channel_pembayaran_id' => 10,
                'type'                  => 'E-WALLET',
                'type_transaksi'        => 'Terima',
                'nama_channel'          => 'DANA',
                'kode_xendit'           => 'DANA',
                'xendit_fee'            => '',
                'xendit_fee_percent'    => 1.5,
                'kode_midtrans'         => '',
                'midtrans_fee'          => '',
                'midtrans_fee_percent'  => '',
                'kode_ipaymu'           => '',
                'ipaymu_fee'            => '',
                'ipaymu_fee_percent'    => '',
                'use_payment_gateway'   => 'xendit',
                'get_profit_fee'        => 0.5,
                'get_profit_percent'    => '',
                'status_channel'        => 'NonAktif'                'created_at'            => Time::now(),
                'update_at'             => Time::now()
            ],
            [
                'channel_pembayaran_id' => 11,
                'type'                  => 'E-WALLET',
                'type_transaksi'        => 'Terima',
                'nama_channel'          => 'LINK AJA',
                'kode_xendit'           => 'LINKAJA',
                'xendit_fee'            => '',
                'xendit_fee_percent'    => 1.5,
                'kode_midtrans'         => '',
                'midtrans_fee'          => '',
                'midtrans_fee_percent'  => '',
                'kode_ipaymu'           => '',
                'ipaymu_fee'            => '',
                'ipaymu_fee_percent'    => '',
                'use_payment_gateway'   => 'xendit',
                'get_profit_fee'        => 0.5,
                'get_profit_percent'    => '',
                'status_channel'        => 'NonAktif'                'created_at'            => Time::now(),
                'update_at'             => Time::now()
            ],
            // QRCODE
            [
                'channel_pembayaran_id' => 11,
                'type'                  => 'QRIS',
                'type_transaksi'        => 'Terima',
                'nama_channel'          => 'QRIS',
                'kode_xendit'           => 'QRIS',
                'xendit_fee'            => '',
                'xendit_fee_percent'    => 0.7,
                'kode_midtrans'         => '',
                'midtrans_fee'          => '',
                'midtrans_fee_percent'  => '',
                'kode_ipaymu'           => '',
                'ipaymu_fee'            => '',
                'ipaymu_fee_percent'    => '',
                'use_payment_gateway'   => 'xendit',
                'get_profit_fee'        => 0.3,
                'get_profit_percent'    => '',
                'status_channel'        => 'NonAktif'                'created_at'            => Time::now(),
                'update_at'             => Time::now()
            ],
            // Retail Outlet
            [
                'channel_pembayaran_id' => 12,
                'type'                  => 'RETAIL OUTLET',
                'type_transaksi'        => 'Terima',
                'nama_channel'          => 'INDOMARET',
                'kode_xendit'           => 'INDOMARET',
                'xendit_fee'            => 5000,
                'xendit_fee_percent'    => '',
                'kode_midtrans'         => '',
                'midtrans_fee'          => '',
                'midtrans_fee_percent'  => '',
                'kode_ipaymu'           => '',
                'ipaymu_fee'            => '',
                'ipaymu_fee_percent'    => '',
                'use_payment_gateway'   => 'xendit',
                'get_profit_fee'        => '',
                'get_profit_percent'    => 1000,
                'status_channel'        => 'NonAktif',
                'created_at'            => Time::now(),
                'update_at'             => Time::now()
            ],
            [
                'channel_pembayaran_id' => 13,
                'type'                  => 'RETAIL OUTLET',
                'type_transaksi'        => 'Terima',
                'nama_channel'          => 'ALFAMART',
                'kode_xendit'           => 'ALFAMART',
                'xendit_fee'            => 5000,
                'xendit_fee_percent'    => '',
                'kode_midtrans'         => '',
                'midtrans_fee'          => '',
                'midtrans_fee_percent'  => '',
                'kode_ipaymu'           => '',
                'ipaymu_fee'            => '',
                'ipaymu_fee_percent'    => '',
                'use_payment_gateway'   => 'xendit',
                'get_profit_fee'        => '',
                'get_profit_percent'    => 1000,
                'status_channel'        => 'NonAktif',
                'created_at'            => Time::now(),
                'update_at'             => Time::now()
            ],
            // disbursement / kirim uang
            [
                'channel_pembayaran_id' => 14,
                'type'                  => 'DISBURSEMENT',
                'type_transaksi'        => 'Kirim',
                'nama_channel'          => 'Kirim Mandiri',
                'kode_xendit'           => 'MANDIRI',
                'xendit_fee'            => 5000,
                'xendit_fee_percent'    => '',
                'kode_midtrans'         => '',
                'midtrans_fee'          => '',
                'midtrans_fee_percent'  => '',
                'kode_ipaymu'           => '',
                'ipaymu_fee'            => '',
                'ipaymu_fee_percent'    => '',
                'use_payment_gateway'   => 'xendit',
                'get_profit_fee'        => '',
                'get_profit_percent'    => 1000,
                'status_channel'        => 'NonAktif',
                'created_at'            => Time::now(),
                'update_at'             => Time::now()
            ],
            [
                'channel_pembayaran_id' => 15,
                'type'                  => 'DISBURSEMENT',
                'type_transaksi'        => 'Kirim',
                'nama_channel'          => 'Kirim BRI',
                'kode_xendit'           => 'BRI',
                'xendit_fee'            => 5000,
                'xendit_fee_percent'    => '',
                'kode_midtrans'         => '',
                'midtrans_fee'          => '',
                'midtrans_fee_percent'  => '',
                'kode_ipaymu'           => '',
                'ipaymu_fee'            => '',
                'ipaymu_fee_percent'    => '',
                'use_payment_gateway'   => 'xendit',
                'get_profit_fee'        => '',
                'get_profit_percent'    => 1000,
                'status_channel'        => 'NonAktif',
                'created_at'            => Time::now(),
                'update_at'             => Time::now()
            ],
            [
                'channel_pembayaran_id' => 16,
                'type'                  => 'DISBURSEMENT',
                'type_transaksi'        => 'Kirim',
                'nama_channel'          => 'Kirim BNI',
                'kode_xendit'           => 'BNI',
                'xendit_fee'            => 5000,
                'xendit_fee_percent'    => '',
                'kode_midtrans'         => '',
                'midtrans_fee'          => '',
                'midtrans_fee_percent'  => '',
                'kode_ipaymu'           => '',
                'ipaymu_fee'            => '',
                'ipaymu_fee_percent'    => '',
                'use_payment_gateway'   => 'xendit',
                'get_profit_fee'        => '',
                'get_profit_percent'    => 1000,
                'status_channel'        => 'NonAktif',
                'created_at'            => Time::now(),
                'update_at'             => Time::now()
            ],
            [
                'channel_pembayaran_id' => 17,
                'type'                  => 'DISBURSEMENT',
                'type_transaksi'        => 'Kirim',
                'nama_channel'          => 'Kirim BCA',
                'kode_xendit'           => 'BCA',
                'xendit_fee'            => 5000,
                'xendit_fee_percent'    => '',
                'kode_midtrans'         => '',
                'midtrans_fee'          => '',
                'midtrans_fee_percent'  => '',
                'kode_ipaymu'           => '',
                'ipaymu_fee'            => '',
                'ipaymu_fee_percent'    => '',
                'use_payment_gateway'   => 'xendit',
                'get_profit_fee'        => '',
                'get_profit_percent'    => 1000,
                'status_channel'        => 'NonAktif',
                'created_at'            => Time::now(),
                'update_at'             => Time::now()
            ],
            [
                'channel_pembayaran_id' => 18,
                'type'                  => 'DISBURSEMENT',
                'type_transaksi'        => 'Kirim',
                'nama_channel'          => 'Kirim BJB',
                'kode_xendit'           => 'BJB',
                'xendit_fee'            => 5000,
                'xendit_fee_percent'    => '',
                'kode_midtrans'         => '',
                'midtrans_fee'          => '',
                'midtrans_fee_percent'  => '',
                'kode_ipaymu'           => '',
                'ipaymu_fee'            => '',
                'ipaymu_fee_percent'    => '',
                'use_payment_gateway'   => 'xendit',
                'get_profit_fee'        => '',
                'get_profit_percent'    => 1000,
                'status_channel'        => 'NonAktif',
                'created_at'            => Time::now(),
                'update_at'             => Time::now()
            ],
            [
                'channel_pembayaran_id' => 19,
                'type'                  => 'DISBURSEMENT',
                'type_transaksi'        => 'Kirim',
                'nama_channel'          => 'Kirim PERMATA',
                'kode_xendit'           => 'PERMATA',
                'xendit_fee'            => 5000,
                'xendit_fee_percent'    => '',
                'kode_midtrans'         => '',
                'midtrans_fee'          => '',
                'midtrans_fee_percent'  => '',
                'kode_ipaymu'           => '',
                'ipaymu_fee'            => '',
                'ipaymu_fee_percent'    => '',
                'use_payment_gateway'   => 'xendit',
                'get_profit_fee'        => '',
                'get_profit_percent'    => 1000,
                'status_channel'        => 'NonAktif',
                'created_at'            => Time::now(),
                'update_at'             => Time::now()
            ],
            [
                'channel_pembayaran_id' => 20,
                'type'                  => 'DISBURSEMENT',
                'type_transaksi'        => 'Kirim',
                'nama_channel'          => 'Kirim SAMPOERNA',
                'kode_xendit'           => 'SAHABAT_SAMPOERNA',
                'xendit_fee'            => 5000,
                'xendit_fee_percent'    => '',
                'kode_midtrans'         => '',
                'midtrans_fee'          => '',
                'midtrans_fee_percent'  => '',
                'kode_ipaymu'           => '',
                'ipaymu_fee'            => '',
                'ipaymu_fee_percent'    => '',
                'use_payment_gateway'   => 'xendit',
                'get_profit_fee'        => '',
                'get_profit_percent'    => 1000,
                'status_channel'        => 'NonAktif',
                'created_at'            => Time::now(),
                'update_at'             => Time::now()
            ],
            [
                'channel_pembayaran_id' => 21,
                'type'                  => 'DISBURSEMENT',
                'type_transaksi'        => 'Kirim',
                'nama_channel'          => 'Kirim BSI',
                'kode_xendit'           => 'BSI',
                'xendit_fee'            => 5000,
                'xendit_fee_percent'    => '',
                'kode_midtrans'         => '',
                'midtrans_fee'          => '',
                'midtrans_fee_percent'  => '',
                'kode_ipaymu'           => '',
                'ipaymu_fee'            => '',
                'ipaymu_fee_percent'    => '',
                'use_payment_gateway'   => 'xendit',
                'get_profit_fee'        => '',
                'get_profit_percent'    => 1000,
                'status_channel'        => 'NonAktif',
                'created_at'            => Time::now(),
                'update_at'             => Time::now()
            ],
            [
                'channel_pembayaran_id' => 22,
                'type'                  => 'DISBURSEMENT',
                'type_transaksi'        => 'Kirim',
                'nama_channel'          => 'Kirim OVO',
                'kode_xendit'           => 'OVO',
                'xendit_fee'            => 5000,
                'xendit_fee_percent'    => '',
                'kode_midtrans'         => '',
                'midtrans_fee'          => '',
                'midtrans_fee_percent'  => '',
                'kode_ipaymu'           => '',
                'ipaymu_fee'            => '',
                'ipaymu_fee_percent'    => '',
                'use_payment_gateway'   => 'xendit',
                'get_profit_fee'        => '',
                'get_profit_percent'    => 1000,
                'status_channel'        => 'NonAktif',
                'created_at'            => Time::now(),
                'update_at'             => Time::now()
            ],
            [
                'channel_pembayaran_id' => 23,
                'type'                  => 'DISBURSEMENT',
                'type_transaksi'        => 'Kirim',
                'nama_channel'          => 'Kirim DANA',
                'kode_xendit'           => 'DANA',
                'xendit_fee'            => 5000,
                'xendit_fee_percent'    => '',
                'kode_midtrans'         => '',
                'midtrans_fee'          => '',
                'midtrans_fee_percent'  => '',
                'kode_ipaymu'           => '',
                'ipaymu_fee'            => '',
                'ipaymu_fee_percent'    => '',
                'use_payment_gateway'   => 'xendit',
                'get_profit_fee'        => '',
                'get_profit_percent'    => 1000,
                'status_channel'        => 'NonAktif',
                'created_at'            => Time::now(),
                'update_at'             => Time::now()
            ],
            [
                'channel_pembayaran_id' => 24,
                'type'                  => 'DISBURSEMENT',
                'type_transaksi'        => 'Kirim',
                'nama_channel'          => 'Kirim GOPAY',
                'kode_xendit'           => 'GOPAY',
                'xendit_fee'            => 5000,
                'xendit_fee_percent'    => '',
                'kode_midtrans'         => '',
                'midtrans_fee'          => '',
                'midtrans_fee_percent'  => '',
                'kode_ipaymu'           => '',
                'ipaymu_fee'            => '',
                'ipaymu_fee_percent'    => '',
                'use_payment_gateway'   => 'xendit',
                'get_profit_fee'        => '',
                'get_profit_percent'    => 1000,
                'status_channel'        => 'NonAktif',
                'created_at'            => Time::now(),
                'update_at'             => Time::now()
            ],
        ];

        $this->db->table('channel_pembayaran')->insertBatch($data);
    }
}